Repository danger/danger, pull requests merged in 2019-03, with the labels that each got.

#1096 Secure code-of-conduct links in readme
  README.md
Labels: Enhancement, PR, Please Review Me!

#1098 Remove trailing whitespace from gitignore
  .gitignore
Labels: Enhancement, PR, Please Review Me!

#1099 Optimize dockerfile labels into 1 layer
  Dockerfile
Labels: Enhancement, PR

#1100 Support Kramdown 2.0+ (requires Ruby 2.3)
  .travis.yml
  CHANGELOG.md
  danger.gemspec
  lib/danger/version.rb
Labels: Merge On Green

#1114 Add Cirrus CI support
  CHANGELOG.md
  lib/danger/ci_source/cirrus.rb
  spec/lib/danger/ci_sources/ci_source_spec.rb
Labels: Enhancement, GitHub, Integration, PR

#1109 Add project URL to Jenkins if available
  CHANGELOG.md
  lib/danger/ci_source/jenkins.rb
Labels: Enhancement, Merge On Green, PR
