Repository danger/danger, pull requests merged in 2019-04, with the labels that each got.

#1115 Support Bitbucket cloud oath
  CHANGELOG.md
  lib/danger/ci_source/bitbucket_pipelines.rb
  lib/danger/ci_source/teamcity.rb
  lib/danger/request_sources/bitbucket_cloud.rb
  lib/danger/request_sources/bitbucket_cloud_api.rb
  spec/fixtures/bitbucket_cloud_api/oauth2_response.json
  spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb
  spec/support/bitbucket_cloud_helper.rb
Labels: Merge On Green

#1119 Update bundler gem
  .circleci/config.yml
  .travis.yml
  Gemfile
  appveyor.yml
Labels: Enhancement, Integration, Local, PR

#1120 Travis: move git commands
  .travis.yml
Labels: PR, Travis CI
